questions = {
    "q1p1": {
        "prompt": "What year are you currently in/are about to enter?",
        "button_text": ["1st year", "2nd year", "3rd year", "4th year"],
        "button_values": [2, 1, 0, -1],
        "next_question": ["q2p1", "q2p1", "q1p2", "q1p2"],
        "button_cnt": 4,
    },
    "q1p2": {
        "prompt": "Were you previously in residence?\n",
        "button_text": ["Yes", "No"],
        "button_values": [-1, 1],
        "next_question": ["q1p3", "q1p3"],
        "button_cnt": 2,
    },
    "q1p3": {
        "prompt": "Have you been denied entry into residency before?\n",
        "button_text": ["Yes", "No"],
        "button_values": [0, 1],
        "next_question": ["q2p1", "q2p1"],
        "button_cnt": 2,
    },
    "q1p4": {
        "prompt": "Please specify the reason on\nwhy you have been denied residency:\n",
        "button_text": ["Did not qualify", "Academic Probation", "Other"],
        "button_values": [1, -1, -1],
        "next_question": ["q2p1", "q2p1", "q2p1"],
        "button_cnt": 3,
    },
    "q2p1": {
        "prompt": " Are you a full-time or part-time student?\n",
        "button_text": ["Full-time", "Part-time"],
        "button_values": [1, -1],
        "next_question": ["q2p2", "q2p2"],
        "button_cnt": 2,
    },
    "q2p2": {
        "prompt": "How many courses are you taking in the upcoming semester?\n",
        "button_text": ["2.0+", "1.5", "1.0", "0.5"],
        "button_values": [1, 1, 0, -1],
        "next_question": ["q3p1", "q3p1", "q3p1", "q3p1"],
        "button_cnt": 4,
    },
    "q3p1": {
        "prompt": "What is your age?\n",
        "button_text": ["18-22", "23+"],
        "button_values": [1, -1],
        "next_question": ["q4p1", "q4p1"],
        "button_cnt": 2,
    },
    "q4p1": {
        "prompt": "What is your academic/disciplinary probation status?\n",
        "button_text": [
            "I am in/have been",
            "Possible probabtion soon",
            "I have faced probation",
            "No history of probation",
        ],
        "button_values": [-1, -2, -3, 1],
        "next_question": ["q5p1", "q5p1", "q5p1", "q5p1"],
        "button_cnt": 4,
    },
    "q5p1": {
        "prompt": "Do you plan to live with your parents?\n",
        "button_text": ["Yes", "No"],
        "button_values": [-1, 1],
        "next_question": ["q6p1", "q5p2"],
        "button_cnt": 2,
    },
    "q5p2": {
        "prompt": "Do you love within a 25km radius of the university?\n",
        "button_text": ["Yes", "No"],
        "button_values": [-1, 1],
        "next_question": ["q6p1", "q6p1"],
        "button_cnt": 2,
    },
    "q6p1": {
        "prompt": "Are you an international student?\n",
        "button_text": ["Yes", "No"],
        "button_values": [1, 0],
        "next_question": ["q7p1", "q7p1"],
        "button_cnt": 2,
    },
    "q7p1": {
        "prompt": "Do you have a physical disability?\n",
        "button_text": ["Yes", "No"],
        "button_values": [1, -1],
        "next_question": ["q7p2", "q8p1"],
        "button_cnt": 2,
    },
    "q7p2": {
        "prompt": "Is the physical disability persistent or prolonged?\n",
        "button_text": ["Yes", "No"],
        "button_values": [1, 0],
        "next_question": ["q7p3", "q7p3"],
        "button_cnt": 2,
    },
    "q7p3": {
        "prompt": "Are any special accommodations\nneeded for your physical disability?\n",
        "button_text": ["Yes", "No"],
        "button_values": [1, 0],
        "next_question": ["q8p1", "q8p1"],
        "button_cnt": 2,
    },
    "q8p1": {
        "prompt": "Do you have a mental disability?\n",
        "button_text": ["Yes", "No"],
        "button_values": [1, 0],
        "next_question": ["q8p2", "q9p1"],
        "button_cnt": 2,
    },
    "q8p2": {
        "prompt": "Is the mental disability persistent or prolonged?\n",
        "button_text": ["Yes", "No"],
        "button_values": [1, 0],
        "next_question": ["q8p3", "q8p3"],
        "button_cnt": 2,
    },
    "q8p3": {
        "prompt": "Are any special accommodations\nneeded for your mental disability?\n",
        "button_text": ["Yes", "No"],
        "button_values": [1, 0],
        "next_question": ["q9p1", "q9p1"],
        "button_cnt": 2,
    },
    "q9p1": {
        "prompt": "Are you part of an athletics team in the university?\n",
        "button_text": ["Yes", "No"],
        "button_values": [1, -1],
        "next_question": ["q10p1", "q10p1"],
        "button_cnt": 2,
    },
    "q10p1": {
        "prompt": "Are you on OSAP?\n",
        "button_text": ["Yes", "No"],
        "button_values": [1, -1],
        "next_question": ["q10p2", "q11p1"],
        "button_cnt": 2,
    },
    "q10p2": {
        "prompt": "How much is your OSAP?\n",
        "button_text": [">=$3,999", "$4,000 - $6,999", "$7,000+"],
        "button_values": [-1, 1, 2],
        "next_question": ["q11p1", "q11p1", "q11p1"],
        "button_cnt": 3,
    },
    "q11p1": {
        "prompt": "Do you currently have a job on campus?\n",
        "button_text": ["Yes", "No"],
        "button_values": [1, -1],
        "next_question": ["q12p1", "q11p2"],
        "button_cnt": 2,
    },
    "q11p2": {
        "prompt": "Would you be interested in\npursuing a job opportunity on campus?\n",
        "button_text": ["Yes", "No"],
        "button_values": [1, 0],
        "next_question": ["q12p1", "q12p1"],
        "button_cnt": 2,
    },
    "q12p1": {
        "prompt": "Any specific preferences for residency?\n",
        "button_text": ["Private", "Shared", "None"],
        "button_values": [-1, 1, 0],
        "next_question": ["END", "END", "END"],
        "button_cnt": 3,
    },
}
